# Generated by Django 5.2.5 on 2025-09-19 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dateAdded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
