# Generated by Django 5.2.5 on 2025-09-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_item_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unitOfMeasure',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
