# Generated by Django 5.2.5 on 2025-09-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryItems', '0001_initial'),
        ('Items', '0003_item_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitems',
            name='itemID',
            field=models.ForeignKey(blank=True, db_column='itemID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='Items.item'),
        ),
    ]
