# Generated by Django 5.2.4 on 2025-09-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item_unitofmeasure'),
        ('Menus', '0002_alter_menu_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='itemid',
            field=models.ForeignKey(db_column='itemid', default='', on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='Items.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menuItem',
        ),
    ]
