# Generated by Django 5.2.4 on 2025-09-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0003_menu_itemid_menu_price_alter_menu_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
    ]
