# Generated by Django 5.2.5 on 2025-09-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0008_alter_customer_phonenumber'),
        ('Items', '0001_initial'),
        ('Staff', '0004_remove_staff_mobile_alter_staff_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Customer.customer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Staff.staff')),
                ('itemID', models.ForeignKey(db_column='itemID', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Items.item')),
            ],
            options={
                'db_table': 'order_',
            },
        ),
    ]
