# Generated by Django 5.2.5 on 2025-09-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('physicalAddress', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
    ]
