# Generated by Django 5.2.5 on 2025-09-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='employeeID',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='physicalAddress',
        ),
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='region',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
