# Generated by Django 5.2.5 on 2025-09-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_alter_staff_address_alter_staff_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
