# Generated by Django 5.2.5 on 2025-09-08 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_customer_table'),
        ('Staff', '0001_initial'),
    ]

    operations = [
        # First, delete the old Customer model
        migrations.DeleteModel(
            name='Customer',
        ),
        # Then create the new Customer model with the new structure
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('physicalAddress', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='Staff.staff')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
