# Generated by Django 5.2.5 on 2025-09-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20250908_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='employee',
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
