# Generated by Django 5.2.5 on 2025-09-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_remove_customer_employee_customer_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstName',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastName',
            new_name='phoneNumber',
        ),
    ]
