# Generated by Django 5.2.5 on 2025-09-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_rename_firstname_customer_fullname_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
