# Generated by Django 5.2.5 on 2025-09-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_customer_phonenumber_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
