# Generated by Django 5.2.5 on 2025-09-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mambosmsbulk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscampaign',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
        migrations.DeleteModel(
            name='SMSCampaign',
        ),
    ]
